debug: False
#---------------------------------------
#Declare host and port
#-------------------------------------
host: "192.168.1.2"
port: 5012
#------------------------------------------
# Specify template folder
#------------------------------------------------
template: template2
