debug: True
#---------------------------------------
#Declare host and port
#-------------------------------------
host: "172.16.9.78"
port: 5012
https: False
host_dir: '/'
name: file explorer
description: This is a application for file explorer
#------------------------------------------
# Specify template folder
#------------------------------------------------
template_folder: templates
static: C:/dj-apps-2022-05-25/jd-apps/app_manager/static
static_url: /static
api_url: http://172.16.9.78:5432