debug: True
#---------------------------------------
#Declare host and port
#-------------------------------------
host: "192.168.1.2"
port: 5012
#------------------------------------------
# Specify template folder
#------------------------------------------------
template_folder: template
static: C:/code/python/dj/jd-apps/app_manager/static
static_url: /static
