HOST: "172.16.9.78"
IS_HTTPS: False
PORT: 8000

DATABASE:
  ENGINE: 'djongo'
  NAME: 'lv-docs'
  ENFORCE_SCHEMA: False
  CLIENT_:
    host: 192.168.18.36
    port: 27018
    username: 'admin-doc'
    password: '123456'
    authSource: 'lv-docs'
#    replicaSet: rs0
    authMechanism: SCRAM-SHA-1
  CLIENT:
    host: localhost
    port: 27017
    username: ok
    password: yes
    authSource: long_test
#    _replicaSet: rs0
    authMechanism: SCRAM-SHA-1

  LOGGING:
    version: 1
    loggers:
      djongo:
        level: DEBUG
        propagate: False

APPS:
  app_auth: 'auth/'
  api_files: 'api/files/'
  api_apps: 'api/apps/'
  app_file_explorer: 'files/'
  app_manager: ''





LOGIN_URL: "auth/login"
TEMP_UPLOAD_DIR: "C:/code/python/tmp/web"
TEMP_UNZIP_DIR: "C:/code/python/tmp/unzip"
TEMP_UPLOAD_DIR_: "//192.168.18.36/Share/DjangoWeb/temp"
TEMP_UNZIP_DIR_: "//192.168.18.36/Share/DjangoWeb/unzip"
KAFKA:
  BROKERS: [192.168.18.36:9092]