PORT: 8000
ALLOWED_HOSTS: [
                 "192.168.1.2"
]
DATABASE:
  ENGINE: 'djongo'
  NAME: 'long_test'
  ENFORCE_SCHEMA: False
  CLIENT:
    host: localhost
    port: 27017
    username: ok
    password: '123456'
    authSource: long_test
#    _replicaSet: rs0
    authMechanism: SCRAM-SHA-1

  LOGGING:
    version: 1
    loggers:
      djongo:
        level: DEBUG
        propagate: False

APPS:
  app_auth: 'auth/'
  api_files: 'api/files/'
  api_apps: 'api/apps/'
  app_file_explorer: 'files/'
  app_manager: ''





ROOT_URL: "http://192.168.1.2:8000"
LOGIN_URL: "auth/login"
TEMP_UPLOAD_DIR: "C:/code/python/tmp/web"
TEMP_UNZIP_DIR: "C:/code/python/tmp/unzip"