PORT: 8000
ALLOWED_HOSTS: [
                 "172.16.9.78"
]
DATABASE:
  ENGINE: 'djongo'
  NAME: 'lv-docs'
  ENFORCE_SCHEMA: False
  CLIENT:
    host: 192.168.18.36
    port: 27018
    username: 'admin-doc'
    password: '123456'
    authSource: 'lv-docs'
    replicaSet: rs0
    authMechanism: SCRAM-SHA-1
  CLIENT_:
    host: localhost
    port: 27017
    username: ok
    password: '123456'
    authSource: long_test
#    _replicaSet: rs0
    authMechanism: SCRAM-SHA-1

  LOGGING:
    version: 1
    loggers:
      djongo:
        level: DEBUG
        propagate: False

APPS:
  app_auth: 'auth/'
  api_files: 'api/files/'
  api_apps: 'api/apps/'
  app_file_explorer: 'files/'
  app_manager: ''




ROOT_URL: "http://172.16.9.78:8000"
ROOT_URL_: "http://192.168.1.2:8000"
LOGIN_URL: "auth/login"
TEMP_UPLOAD_DIR_: "C:/code/python/tmp/web"
TEMP_UNZIP_DIR_: "C:/code/python/tmp/unzip"
TEMP_UPLOAD_DIR: "//192.168.18.36/Share/DjangoWeb/temp"
TEMP_UNZIP_DIR: "//192.168.18.36/Share/DjangoWeb/unzip"
KAFKA:
  BROKERS: [192.168.18.36:9092]