PORT: 8000
ALLOWED_HOSTS: [
                 "172.16.9.78"
]
DATABASE:
  ENGINE: 'djongo'
  NAME: 'lv-docs'
  ENFORCE_SCHEMA: False
  CLIENT:
    host: 192.168.18.36
    port: 27018
    username: admin-doc
    password: '123456'
    authSource: lv-docs
    replicaSet: rs0
    authMechanism: SCRAM-SHA-1

  LOGGING:
    version: 1
    loggers:
      djongo:
        level: DEBUG
        propagate: False

APPS:
  app_file_explorer: 'files/'
  api_files: 'api/files/'
  api_apps: 'api/apps/'
  app_manager: ''
  app_auth: 'auth/'
ROOT_URL: "http://172.16.9.78:8000"
LOGIN_URL: "auth/login"