PORT: 7001
ALLOWED_HOSTS: [
                 "192.168.1.2"
]
DATABASE:
  ENGINE: 'djongo'
  NAME: 'test'
  ENFORCE_SCHEMA: False
  CLIENT:
    host: localhost
    port: 27017
    username: test
    password: test
    authSource: test
#    replicaSet: None
    authMechanism: SCRAM-SHA-1

  LOGGING:
    version: 1
    loggers:
      djongo:
        level: DEBUG
        propagate: False

APPS:
  app_file_explorer: 'files/'
  api_files: 'api/files/'