host: 192.168.18.36
port: 27018
username: 'admin-doc'
password: '123456'
authSource: 'lv-docs'
replicaSet: rs0
authMechanism: SCRAM-SHA-1

#host: localhost
#port: 27017
#username: 'ok'
#password: 'yes'
#authSource: 'long-test'
##replicaSet: rs0
#authMechanism: SCRAM-SHA-1