api: api
# Cấu hình thư mục static
# Đường dẫn tương đối sẽ bắt đầu bằng ./
static: C:/code/python/jd-apps/app_manager/static
login: login
temp_upload_dir: ./temp_upload
jinja_templates_dir: ./templates
root_url: http://localhost:8001
api_url: http://localhost:8001/api