api: api
# Cấu hình thư mục static
# Đường dẫn tương đối sẽ bắt đầu bằng ./
static: C:/dj-apps-2022-05-25/jd-apps/app_manager/static
login: login
temp_upload_dir: //192.168.18.36/Share/DjangoWeb/temp
jinja_templates_dir: ./templates
root_url: http://127.0.0.1:8001
api_url: http://127.0.0.1:8001/api
jwt:
  secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  algorithm: HS256
  access_token_expire_minutes: 30
