"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
HOST = "0.0.0.0"
IS_HTTPS = False
PORT = None
import mimetypes
import sys

mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("text/css", ".css", True)
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import ReCompact.web
import ReEngine
ReCompact.web.set_working_dir(BASE_DIR)
config_path = BASE_DIR.absolute().joinpath("config.yaml")
ReEngine.init(str(config_path))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v)o9^1!i4zx0-tx=k_g*c$zqq^1=$$2tjwl0(ipp_$_eo&i0$h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    HOST
]
LOGIN_URL = "auth/login"
CORS_ALLOW_ALL_ORIGINS = True
TEMP_UPLOAD_DIR =r'\\192.168.18.36\Share\DjangoWeb'
TEMP_UNZIP_DIR = r'\\192.168.18.36\Share\UnzipDjangoWeb'

# Application definition
# from apps.file_explorer.apps import FileExplorerConfig
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'ReEngine.UrlCaseInsensitive.middleware.ResolveCaseInsesitive',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]
import ReEngine
import os
ReEngine.init(os.path.join(BASE_DIR,"config.yaml"))
ROOT_URLCONF = 'web.urls'
TEMPLATES_DIR=[]
for k,v in ReEngine.info["APPS"].items():
    TEMPLATES_DIR.append(os.path.join(BASE_DIR,k,"templates"))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
KAFKA = dict(
    BROKERS=["192.168.18.36:9092"]
)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
import ReEngine
ROOT_URL = f"http://0.0.0.0:8000"
ReEngine.apply_settings_modudle(sys.modules[__name__])
if IS_HTTPS:
    if PORT is not None :
        ROOT_URL = f"https://{HOST}:{PORT}"
    else:
        ROOT_URL = f"https://{HOST}"
else:
    if PORT is not None:
        ROOT_URL = f"http://{HOST}:{PORT}"
    else:
        ROOT_URL = f"http://{HOST}"
STATIC_URL = '/static/'
STATICFILES_DIRS = [

            ]
for k,v in ReEngine.info["APPS"].items():
    if v=="":
        staic_path_of_app = os.path.join(BASE_DIR, k, "static")
        STATICFILES_DIRS.append(staic_path_of_app)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID=1
ALLOWED_HOSTS = [HOST]



